# Generated by Django 4.2 on 2023-06-29 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='domains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=500)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pfam_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_id', models.CharField(max_length=256)),
                ('domain_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='protein_sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('sequence', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxa_id', models.CharField(max_length=256)),
                ('clade', models.CharField(max_length=100)),
                ('genus', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='proteins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=256)),
                ('length', models.IntegerField()),
                ('taxa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.taxonomy')),
            ],
        ),
        migrations.CreateModel(
            name='protein_domain_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domains')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.proteins')),
            ],
        ),
        migrations.AddField(
            model_name='domains',
            name='protein',
            field=models.ManyToManyField(through='api.protein_domain_link', to='api.proteins'),
        ),
    ]
