# Generated by Django 4.2 on 2023-06-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pfam_id',
        ),
        migrations.AddField(
            model_name='domains',
            name='domain_description',
            field=models.CharField(default=343, max_length=500),
            preserve_default=False,
        ),
    ]
